---
collections:
  - { name: ansible.controller, version: 4.5.6 }
  - { name: community.general, version: 9.0.1 }
  - { name: community.postgresql, version: 3.4.1 }
  - { name: community.sops, version: 1.6.7 }
  - { name: infra.aap_utilities, version: 2.5.1 }
  - { name: infra.ah_configuration, version: 2.0.6 }
  - { name: infra.controller_configuration, version: 2.8.1 }
  - { name: infra.eda_configuration, version: 1.1.0 }
