---
- name: Ensure the Automation Hub username is updated
  community.postgresql.postgresql_query:
    db: "pulp"
    login_host: "localhost"
    login_user: "postgres"
    login_password: "{{ admin_password }}"
    query: "UPDATE galaxy_user SET username = %s WHERE id = 1"
    positional_args:
      - "{{ admin_username }}"

- name: Ensure the Automation Hub token is created
  community.postgresql.postgresql_query:
    db: "pulp"
    login_host: "localhost"
    login_user: "postgres"
    login_password: "{{ admin_password }}"
    query: >-
      INSERT INTO authtoken_token (key, created, user_id)
      VALUES (%s, NOW(), 1)
      ON CONFLICT (user_id)
      DO UPDATE SET
        key = EXCLUDED.key,
        created = EXCLUDED.created
    positional_args:
      - "{{ automation_hub_token }}"

- name: Ensure the Automation Controller token is created
  community.postgresql.postgresql_query:
    db: "awx"
    login_host: "localhost"
    login_user: "postgres"
    login_password: "{{ admin_password }}"
    query: >-
      INSERT INTO main_oauth2accesstoken (user_id, description, token, scope, expires, modified, created, updated)
      VALUES (1, 'Event Driven Ansible', %s, 'write', NOW() + interval '1000 years', NOW(), NOW(), NOW())
      ON CONFLICT (token)
      DO UPDATE SET
        user_id = EXCLUDED.user_id,
        description = EXCLUDED.description,
        scope = EXCLUDED.scope,
        expires = EXCLUDED.expires,
        modified = EXCLUDED.modified,
        updated = EXCLUDED.updated
    positional_args:
      - "{{ automation_controller_token }}"
